### ISSUE TITLE
State of this library

### ISSUE THREAD

**Issue by 19h** [d-e-s-o/polyio#1] opened 2020-08-02 20:24 UTC
Hey Daniel,

I've only now became aware of your efforts with your library -- I was working on a similar library the last few weeks (https://github.com/19h/polygon-rs). It's generated from the swagger API specification, so it's definitely a bit convoluted.

Although I find your codebase exceptionally clean, I couldn't really find any mention of forex, stocks or crypto in this library. How do you achieve calls like /v2/snapshot/locale/us/markets/stocks/tickers/{ticker} with your project?

The way you exposed the WebSocket client API is sweet.

Thanks!

**Comment by d-e-s-o** [comment] 2020-08-02 20:55
Hey Kenan,

thanks for taking a look. The crate is very much requirements driven, meaning that I've only hooked up the endpoints that I needed myself. I wanted to have test coverage for each and so having some blanket implementations was not an option (Polygon.io has repeatedly proven to be not providing a stable API nor stable query results for past data).

I am only doing stocks right now and as such forex and crypto functionality is not present. `/v2/snapshot/locale/us/markets/stocks/tickers/{ticker}` specifically is not hooked up. Should be reasonably easy to do, though, and I'd be happy to accept pull requests.

Edit: In general [`polycli`](https://github.com/d-e-s-o/polycli/blob/master/src/main.rs) illustrates usage of a good subset of the endpoints.

**Comment by 19h** [comment] 2020-08-02 21:38
Thanks for elaborating!

Precisely because of this point I chose not to implement the client by hand:

> Polygon.io has repeatedly proven to be not providing a stable API nor stable query results for past data

I've opened several issues for things like that, so I share that pain:

- https://github.com/polygon-io/ui-swagger/pull/78
- https://github.com/polygon-io/ui-swagger/issues/79
- https://github.com/polygon-io/ui-swagger/issues/80

Based on the state of those issues I'm afraid that either the endpoints at PR are not entirely tested, the documentation is secondary or there's more critical issues for them to handle at this point (stability for endpoints required by enterprise customers?). Either way, I'll play with your project and try to get a feeling for its ergonomics.

Something I'd love to do either way is to have some kind of mashup between your websocket client impl and my generated REST api, at least as a "boring" alternative to your repo (the entire codebase on my client can be regenerated from the API spec (https://polygon.io/docs/swagger.json). I thought that way everyone benefits from an improved documentation as there'll be an actual requirement for a stable API spec.

Really dig polycli -- that's quite some amazing work you did here.

**Comment by d-e-s-o** [comment] 2020-08-02 22:07
> I've opened several issues for things like that, so I share that pain:
> 
> * [polygon-io/ui-swagger#78](https://github.com/polygon-io/ui-swagger/pull/78)
> * [polygon-io/ui-swagger#79](https://github.com/polygon-io/ui-swagger/issues/79)
> * [polygon-io/ui-swagger#80](https://github.com/polygon-io/ui-swagger/issues/80)
> 
> Based on the state of those issues I'm afraid that either the endpoints at PR are not entirely tested, the documentation is secondary or there's more critical issues for them to handle at this point (stability for endpoints required by enterprise customers?).

Definitely. I used it extensively (as in: every trading day) for a month or so and I was hitting issue after issue. Their claims about corporate customers are nothing but hot air. To their credit, though, if you contact customer support directly they are usually very responsive and they actually (!) fix issues that you point out.

> Something I'd love to do either way is to have some kind of mashup between your websocket client impl and my generated REST api, at least as a "boring" alternative to your repo (the entire codebase on my client can be regenerated from the API spec (https://polygon.io/docs/swagger.json). I thought that way everyone benefits from an improved documentation as there'll be an actual requirement for a stable API spec.

Sounds great! I have a rough idea of what swagger can do, but based on (arguably very little) experience the bindings generated are generally not super nice to use -- but at least you eliminate *some* sources of error and get a lot for free.

I am dipping my toes into WebAssembly and enabled the crate for usage in browsers (only the API stuff, no WebSocket support right now).

**Comment by 19h** [comment] 2020-08-03 00:27
I'm currently getting a 404 with polycli.

```
19h@rtx ~/dev/polycli $ polycli ticker get AAPL 
failed to retrieve ticker information: HTTP status 404 Not Found: 404 page not found
```

Was the endpoint removed?

**Comment by d-e-s-o** [comment] 2020-08-03 02:35
> I'm currently getting a 404 with polycli.
> 
> ```
> 19h@rtx ~/dev/polycli $ polycli ticker get AAPL 
> failed to retrieve ticker information: HTTP status 404 Not Found: 404 page not found
> ```
> 
> Was the endpoint removed?

It's actually expected behavior from what I recall. This endpoint results in 404 [if the market is closed](https://docs.rs/polyio/0.5.0/polyio/api/ticker/enum.GetError.html#variant.NotFound). It's stupid but that's what `polygon.io` decided on.

**Comment by 19h** [comment] 2020-08-03 14:37
I don't think so and it didn't happen anymore during my testing. It's still happening. If you don't have an active key anymore, let me know.. :-) It would be pretty reasonable if Polygon provided us with semi-permanent keys because we won't be able to maintaine any of these libraries once we have no access anymore ..

Anyway.. still happening:

```
19h@rtx ~/dev/polycli $ polycli ticker get AAPL
failed to retrieve ticker information: HTTP status 404 Not Found: 404 page not found
```

I'm sure this is related to my initial question about the paths. They include the market type explicitly in the URL now.

Talking about API contract stability ..

<img width="934" alt="CleanShot 2020-08-03 at 16 27 29@2x" src="https://user-images.githubusercontent.com/280212/89193756-bf5c3500-d5a6-11ea-9033-2ed5866e8231.png">

**Comment by d-e-s-o** [comment] 2020-08-03 16:00
> I don't think so and it didn't happen anymore during my testing. It's still happening. If you don't have an active key anymore, let me know.. :-) It would be pretty reasonable if Polygon provided us with semi-permanent keys because we won't be able to maintaine any of these libraries once we have no access anymore ..
> 
> Anyway.. still happening:
> 
> ```
> 19h@rtx ~/dev/polycli $ polycli ticker get AAPL
> failed to retrieve ticker information: HTTP status 404 Not Found: 404 page not found
> ```
> 
> I'm sure this is related to my initial question about the paths. They include the market type explicitly in the URL now.

True, it no longer works. Sigh. So what is the path? I got told we now have to search (.../tickers endpoint & `?search` or so).

> Talking about API contract stability ..

Ugh. That's bad. So apparently the conditions are now optional. Rest assured it's [not](https://github.com/d-e-s-o/polyio/commit/2eb6fe228cb2dc0516294a166e0ada95983b3c26) the [first time](https://github.com/d-e-s-o/polyio/commit/5e5e2857a4e0fa06ccc0872e18ca544b7cb14814) they have made changes like that. Honestly, I have no idea what to do. Their stuff is borderline useless from what I can tell. Would the swagger stuff help here? Is it marked as optional in there (I couldn't find the right "c" off hand; or does it not capture the websocket schema at all)?

**Comment by d-e-s-o** [comment] 2020-08-03 16:27
> Ugh. That's bad. So apparently the conditions are now optional.

They confirmed it's optional. Of course, it always has been implicitly optional, because they could just have sent an empty array. But yeah. It's [hopeless](https://github.com/d-e-s-o/polyio/commit/2c6c89a55588d15f568fff0e8e79066fa65b5bb0). They just have no idea what they are doing is my impression.

**Comment by 19h** [comment] 2020-08-03 16:51
Initially I had hoped this was covered in my impl but, unfortunately, yes, the WebSocket protocol contract isn't covered by the swagger specification.

The paths for obtaining the ticker data are now specific to the "markets":

https://github.com/19h/polygon-rs/blob/master/src/apis/stocks_equities_api.rs#L605
https://github.com/19h/polygon-rs/blob/master/src/apis/forex_currencies_api.rs#L432
https://github.com/19h/polygon-rs/blob/master/src/apis/crypto_api.rs#L519

Funnily enough it seems they're all just the same endpoint with a different name. You can query AAPL via both the forex and crypto endpoints.

That said, going through the spec, judging from my tests, the `c` isn't optional via REST.

https://github.com/19h/polygon-rs/blob/master/src/models/aggv2.rs#L29

There are a lot of fields marked as required which are actually optional ..

<img width="787" alt="CleanShot 2020-08-03 at 18 50 16@2x" src="https://user-images.githubusercontent.com/280212/89206928-3bac4380-d5ba-11ea-9282-66ec5ddcbad8.png">
<img width="550" alt="CleanShot 2020-08-03 at 18 50 04@2x" src="https://user-images.githubusercontent.com/280212/89206930-3cdd7080-d5ba-11ea-9c78-9ae2621928be.png">
<img width="807" alt="CleanShot 2020-08-03 at 18 49 53@2x" src="https://user-images.githubusercontent.com/280212/89206931-3d760700-d5ba-11ea-94b0-81d9b9dad49d.png">
<img width="1029" alt="CleanShot 2020-08-03 at 18 49 45@2x" src="https://user-images.githubusercontent.com/280212/89206933-3d760700-d5ba-11ea-908f-305fc9507bbc.png">
<img width="873" alt="CleanShot 2020-08-03 at 18 49 35@2x" src="https://user-images.githubusercontent.com/280212/89206935-3e0e9d80-d5ba-11ea-91ce-faa09ee1e484.png">
<img width="509" alt="CleanShot 2020-08-03 at 18 49 30@2x" src="https://user-images.githubusercontent.com/280212/89206937-3e0e9d80-d5ba-11ea-8a0d-e21b02e8c324.png">
<img width="559" alt="CleanShot 2020-08-03 at 18 49 23@2x" src="https://user-images.githubusercontent.com/280212/89206938-3ea73400-d5ba-11ea-9087-f6e475ee2d2e.png">

**Comment by eikeon** [comment] 2021-06-12 21:46
given this discussion; is the Alpaca Market Data v2 API any better?

**Comment by d-e-s-o** [comment] 2021-06-13 00:53
> given this discussion; is the Alpaca Market Data v2 API any better?

I haven't use it, so I am not sure. There were a couple of threads about it in the Alpaca user forum and the reports were mixed from what I recall. But those were from when stuff was in beta, so that may have improved. If you are willing to pay, they may be reasonable, but there should be plenty of alternatives then as well (in the same price range), some of which presumably more mature.
Personally, I try to stay away from them given their sub-par support, quality in general (also backwards incompatible changes [though way fewer than with Polygon], broken patches pushed, wrong statements reported), the very little insight they provided into what they are doing, why something broke etc., their perceived don't-care-about-users attitude, and bad availability. So paying them a monthly fee is out of a question for me.

**Comment by eikeon** [comment] 2021-06-13 14:58
Thank you for the feedback; agreed re: impression. 

Mostly looking for what's out there on the free or low end of the spectrum and was hoping the likes of https://polygon.io/docs/get_v2_snapshot_locale_us_markets_stocks_tickers_anchor would fall into such a tier.

Perhaps I'll stick to the likes of the Aggregate Bars API for now -- probably better fits my use case anyway.

And thank you re: polyio library!

**Closed as completed** 2022-03-07 02:12 UTC
